FROM jrei/systemd-ubuntu:20.04
RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install flask
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install msgpack-python
RUN pip3 install requests
RUN pip3 install datetime
RUN pip3 install bs4
RUN pip3 install pymysql
RUN pip3 install thread6
RUN apt-get install wget -y
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update -y
RUN apt-get install google-chrome-stable -y
RUN wget -N https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip
RUN apt-get install unzip -y
RUN unzip chromedriver_linux64.zip
RUN python3 -m pip install --upgrade pip
RUN pip install xlrd
RUN apt-get install xvfb -y
RUN pip install pyvirtualdisplay
RUN pip install selenium
RUN apt install openssh-server -y
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install uwsgi
RUN apt-get install uwsgi-plugin-python3 
RUN apt-get install nginx